import { Button, VerticalBox, LineEdit } from "std-widgets.slint";


export component AppWindow inherits Window {
    in property <string> results: "";
    callback divide-income(string);
    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 20px;
        Row {
            Text {
                text: "Total Income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }

        Row {
            income := LineEdit {
                placeholder-text: "Enter Your Number";
                font-size: 16px;
                horizontal-alignment: center;
                height: 35px;
            }
        }

        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;
                width: 160px;
                clicked => {
                    divide-income(income.text)
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.results;
                    }
                }
            }
        }
    }
}
